### ISSUE TITLE
near "DROP": syntax error (code 1 SQLITE_ERROR): , while compiling: ALTER TABLE GameEntity DROP COLUMN lastRedirectUrl

### ISSUE THREAD

**Issue by p0058781** [p0058781/AVNGameLauncher#13]
SqlDelight migration is broken on android. Android sqlite doesn't support `DROP`

```
android.database.sqlite.SQLiteException: near "DROP": syntax error (code 1 SQLITE_ERROR): , while compiling: ALTER TABLE GameEntity DROP COLUMN lastRedirectUrl
at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1068)
at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:673)
at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:62)
at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:34)
at android.database.sqlite.SQLiteDatabase.compileStatement(SQLiteDatabase.java:1390)
at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.compileStatement(FrameworkSQLiteDatabase.kt:51)
at app.cash.sqldelight.driver.android.AndroidSqliteDriver$execute$1.invoke(AndroidSqliteDriver.kt:184)
at app.cash.sqldelight.driver.android.AndroidSqliteDriver$execute$1.invoke(AndroidSqliteDriver.kt:184)
at app.cash.sqldelight.driver.android.AndroidSqliteDriver.execute-zeHU3Mk(AndroidSqliteDriver.kt:163)
at app.cash.sqldelight.driver.android.AndroidSqliteDriver.execute(AndroidSqliteDriver.kt:184)
at app.cash.sqldelight.db.SqlDriver$DefaultImpls.execute$default(SqlDriver.kt:63)
at org.skynetsoftware.avnlauncher.data.data.DatabaseImpl$Schema.migrateInternal-ElmaSbI(DatabaseImpl.kt:67)
at org.skynetsoftware.avnlauncher.data.data.DatabaseImpl$Schema.migrate-zeHU3Mk(DatabaseImpl.kt:92)
at org.skynetsoftware.avnlauncher.data.data.DatabaseImpl$Schema.migrate(DatabaseImpl.kt:27)
at app.cash.sqldelight.driver.android.AndroidSqliteDriver$Callback.onUpgrade(AndroidSqliteDriver.kt:215)
at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onUpgrade(FrameworkSQLiteOpenHelper.kt:253)
at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:416)
at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableOrReadableDatabase(FrameworkSQLiteOpenHelper.kt:232)
at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.innerGetDatabase(FrameworkSQLiteOpenHelper.kt:190)
at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getSupportDatabase(FrameworkSQLiteOpenHelper.kt:151)
at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.kt:104)
at app.cash.sqldelight.driver.android.AndroidSqliteDriver$database$2.invoke(AndroidSqliteDriver.kt:41)
at app.cash.sqldelight.driver.android.AndroidSqliteDriver$database$2.invoke(AndroidSqliteDriver.kt:40)
at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
at app.cash.sqldelight.driver.android.AndroidSqliteDriver.getDatabase(AndroidSqliteDriver.kt:40)
at app.cash.sqldelight.driver.android.AndroidSqliteDriver.access$getDatabase(AndroidSqliteDriver.kt:29)
at app.cash.sqldelight.driver.android.AndroidSqliteDriver$executeQuery$1.invoke(AndroidSqliteDriver.kt:192)
at app.cash.sqldelight.driver.android.AndroidSqliteDriver$executeQuery$1.invoke(AndroidSqliteDriver.kt:192)
at app.cash.sqldelight.driver.android.AndroidSqliteDriver.execute-zeHU3Mk(AndroidSqliteDriver.kt:163)
at app.cash.sqldelight.driver.android.AndroidSqliteDriver.executeQuery-0yMERmw(AndroidSqliteDriver.kt:192)
at app.cash.sqldelight.driver.android.AndroidSqliteDriver.executeQuery(AndroidSqliteDriver.kt:29)
at app.cash.sqldelight.SimpleQuery.execute(Query.kt:98)
at app.cash.sqldelight.ExecutableQuery.executeAsList(Query.kt:174)
at org.skynetsoftware.avnlauncher.data.repository.GamesRepositoryImpl$all$2.invokeSuspend(GamesRepositoryImpl.kt:34)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-03-13 14:15:26.671  5324-5324  org.skynet...gger_jvmKt org.skynetsoftware.avnlauncher       E  	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineName(org.skynetsoftware.avnlauncher.ui.screen.main.MainScreen:org.skynetsoftware.avnlauncher.ui.viewmodel.GamesScreenModel:default:ScreenModelCoroutineScope), StandaloneCoroutine{Cancelling}@3a8a4c7, Dispatchers.Main.immediate]
```

**Comment by p0058781** [comment]
Android support dropped
