### ISSUE TITLE
Crash when removing missing executable path

### ISSUE THREAD

**Issue by r37r05p3C7** [p0058781/AVNGameLauncher#33]
I've had 1 game in the database, app crashed on launch. Successfully launched again after removing game entry from db.

Error from the log:
```
2024-03-15 16:49:52,034 [UpdateCheckerImpl$checkForUpdates$3] INFO : Checking 1 games for updates
2024-03-15 16:49:52,034 [Logger_jvmKt] ERROR: null
java.util.ConcurrentModificationException
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source)
	at java.base/java.util.LinkedHashMap$LinkedKeyIterator.next(Unknown Source)
	at org.skynetsoftware.avnlauncher.utils.ExecutableFinderDesktop.removeNonExistingExecutables(Executable.desktop.kt:94)
	at org.skynetsoftware.avnlauncher.utils.ExecutableFinderDesktop.validateExecutables(Executable.desktop.kt:37)
	at org.skynetsoftware.avnlauncher.ui.viewmodel.GamesScreenModel$1.invokeSuspend(GamesScreenModel.kt:86)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineName(org.skynetsoftware.avnlauncher.ui.screen.main.MainScreen:org.skynetsoftware.avnlauncher.ui.viewmodel.GamesScreenModel:default:ScreenModelCoroutineScope), StandaloneCoroutine{Cancelling}@1479e0ed, Dispatchers.Main.immediate]
```

**Comment by p0058781** [comment]
Looks like something with removing non-existing executables from db (which happens on app launch)
Do you remember if that was the case for you, executable path set for game but doesn't exist anymore ?
